begin;
do $$
declare su uuid; ad uuid; us uuid; a uuid:=gen_random_uuid(); n uuid; oldname text; changed int; denied boolean;
begin
 select id into su from public.profiles where role='super_admin' and not is_blocked limit 1;
 select id into ad from public.profiles where role='user' and not is_blocked limit 1;
 select id into us from public.profiles where role='user' and id<>ad and not is_blocked limit 1;
 if su is null or ad is null or us is null then raise exception 'Missing test roles';end if;
 update public.profiles set role='admin' where id=ad;
 perform set_config('request.jwt.claim.sub',su::text,true);
 insert into public.athletes(id,name,class,gender,created_by) values(a,'QA TRANSACTION ATHLETE','BC1','Masculino',su);
 perform set_config('request.jwt.claim.sub',ad::text,true);
 execute 'set local role authenticated';
 update public.athletes set name='DIRECT EDIT' where id=a;
 get diagnostics changed=row_count;
 if changed<>0 then raise exception 'Admin bypassed correction approval';end if;
 update public.profiles set role='super_admin' where id=ad;
 get diagnostics changed=row_count;
 if changed<>0 then raise exception 'Admin escalated own role';end if;
 perform public.admin_update_athlete(a,'APPROVED QA NAME','BC2','Feminino','Brasil','SP','QA');
 if (select name from public.athletes where id=a)<>'QA TRANSACTION ATHLETE' then raise exception 'Pending edit changed athlete';end if;
 select id into n from public.admin_notifications where source_type='athlete_edit' and change_data->>'athlete_id'=a::text;
 if n is null then raise exception 'Missing correction notification';end if;
 denied:=false;
 begin perform public.resolve_athlete_correction(n,'approved'); exception when others then denied:=true;end;
 if not denied then raise exception 'Admin approved own correction';end if;
 perform set_config('request.jwt.claim.sub',us::text,true);
 if exists(select 1 from public.admin_notifications where id=n) then raise exception 'Another user read request';end if;
 if exists(select 1 from public.scout_sessions where owner_id<>us) then raise exception 'User read another account history';end if;
 denied:=false;
 begin perform public.admin_update_athlete(a,'ILLEGAL','BC1');exception when others then denied:=true;end;
 if not denied then raise exception 'Normal user edited athlete';end if;
 perform set_config('request.jwt.claim.sub',su::text,true);
 perform public.resolve_athlete_correction(n,'approved');
 if (select name from public.athletes where id=a)<>'APPROVED QA NAME' then raise exception 'Super approval failed';end if;
 perform set_config('request.jwt.claim.sub',ad::text,true);
 if (select status from public.admin_notifications where id=n)<>'approved' then raise exception 'Requester cannot see decision';end if;
 insert into public.notification_reads(user_id,notification_id,status) values(ad,n,'approved');
 perform public.admin_update_athlete(a,'REJECTED QA NAME','BC3');
 select id into n from public.admin_notifications where source_type='athlete_edit' and status='pending' and change_data->>'athlete_id'=a::text;
 perform set_config('request.jwt.claim.sub',su::text,true);
 perform public.resolve_athlete_correction(n,'rejected');
 if (select name from public.athletes where id=a)<>'APPROVED QA NAME' then raise exception 'Rejection changed athlete';end if;
 execute 'reset role';
end $$;
rollback;
select 'PASS: admin proposal, direct-edit and role-escalation blocked, super approval/rejection, account isolation, read receipts; all test changes rolled back' as result;
